name: Test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
        python -m pip install --upgrade pip
        pip install -r requestments.txt
      - name: Test with pytest
      - uses: actions/checkout@v4
        run: |
        pip install pytest
        pytest test_main.py
